### ISSUE TITLE
Use constant format specifier to generate constant signals

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_hardcaml#10]
```ocaml
let%hw x = 1h
let%hw y = 0xdh
let%hw z = 0b1010h
let%hw pow2 n x = x @ zero n
let%hw sum = x + y + (pow2 3 (2h + z))
```

**Comment by xguerin** [comment]
@andrewray I propose to resize the signal to the next power of 2 bits. However, the precision will be limited to the capacity of OCaml's `int` size, which is 63 bits.

**Comment by andrewray** [comment]
See `HardCaml.Utils.nbits` which for values >= 0 should produce a bitwidth appropriate for `consti` (when using unsigned arithmetic).

```
consti (HardCaml.Utils.nbits v) v
```

Limiting to int size is reasonable, and could be extended later if needed (although its probably a rare requirement, and can be handled with the likes of `constd`).

**Comment by xguerin** [comment]
Thanks for the pointers. I am pushing a change that will allow this kind of unit testing:

```ocaml
let%hw immediate_const context =
  let x = 1h and y = 0xdh and z = 0b1010h in
  let pow2 n x = x @ zero n in
  let sum = x + y + (pow2 3 (2h + z)) in
  assert_equal sum 206h
```

**Comment by andrewray** [comment]
I am trying to resurrect (and fix) some code related to our discussions on how expression recursion (#2) works, which I think would help here.

Basically, rather than decoding the AST via pattern matching, it uses the generic expression mapper framework to rewrite everything and pick out the interesting parts.  I think this is a more general approach and simpler to implement, but does leave a bunch of error checking to the type checker.
