### ISSUE TITLE
Simplifies the expression matcher using a generic Ast_mapper

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_hardcaml#11]

**Comment by xguerin** [comment]
This version passes all unit tests, so I believe it is fairly complete. I removed support for binary operations with a regular integer as a left hand operator for the moment.

**Comment by andrewray** [comment]
I think you could probably remove the "operators with regular integer" totally to be honest.  The hardware constant is a better approach.

I was wondering about one small extension to hardware constants.  We could detect the 0b010h form and convert it into `constb 010`.  The advantage is having a constant form where we can control the width ie.

```
let%hw mul_by_4 x = x @ 0b00h
let%hw extend_by_2 x = 0b00h @ x
```

**Comment by xguerin** [comment]
Done.

**Comment by andrewray** [comment]
So this is looking rather awesome now!  Two final comments (I promise!).  

First, I wonder if the hardware constant form could be enabled globally and not just within `[%hw]` extensions.  It doesn't clash with anything else, so should be safe.  

Secondly, regarding the `if ... then ... else` construct - here we reuse syntax which means normal if's can't be used within `[%hw]` extensions.  I think I originally had it so that the if is only treated as a mux when written as `if%hw ...`.  Since it is now distinguished with a marker it also wouldn't strictly have to be within a `[%hw]` extension.  I've not thought this through 100% yet and it might not be sensible, but here are some examples.

```
let invert_by_mux d = if%hw d then 0h else 1h

let%hw select_const sel1 sel2 a b c d = (* sel1:bool sel2:signal *) 
  if sel1 then 
    if%hw sel2 then (a+b) else (a-b)
  else
    if%hw sel2 then (c+d) else (c-d)
```

Oh, and a third thing - the `if%hw c then t else f` could be a bit more general if it was converted as

```
mux2 (c <>:. 0) (uresize t max) (uresize f max)
```

but that's really nitpicking...

**Comment by xguerin** [comment]
These all make sense. I'll look into them.
